### ISSUE TITLE
Popup text auto-scaling

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#294] opened 2016-12-02 21:40 UTC
Hello everyone,

I have started work on popup text autoscaling.

@BackOrder  I am fascinated by your approach but I dont understand why it doesnt work on all occassions.
Here is your working code from the other ticket:
```Ruby
Shoes.app(width: 250, height: 250) do
    @menu = stack width: 100, left: 75, top: 100 do end
    @menu.clear do
        @b = background blue, curve: 15
        @b2 = background yellow, curve: 15, left: 2, top: 2, height: @menu.height - 4
        flow margin_left: 12, margin_top: 5 do
            @p = para "Say hello!"
        end
        timer(0) { 
            @b.width = @p.width + 20
            @b2.width = @b.width - 4
        }
    end
end
```
And below you can see my code which does not work.
What is important is the @box where message is set and the timer where the things happen but actually do not. Check the debug results when hovering over elements. Why the @box.width is 0 where at your case it is a valid number?

```Ruby
class Tooltip < Shoes::Widget

    def initialize ()
         motion { |x, y| @move_left = x; @move_top = y }
         @@menu1 = stack;
    end

    def show( options={} )
         @@menu1.clear {    @@menu = stack height: 0 do end.hide }
        offset, high, wide, text, stroke, size, font, back1, back2 = 10, options[:height], options[:width], options[:text], options[:stroke], options[:size], options[:font],  options[:border] || rgb(120,42,5,0.5), options[:background] || rgb(180,150,110,0.7) 
        @@menu.style width: offset + wide, height: offset + high
        menu_left, menu_top = @move_left, @move_top;
        @move_left + @@menu.width >= app.width + offset ? menu_left = @move_left - @@menu.width : nil
        @move_top + @@menu.height >= app.height + offset ? menu_top = @move_top - 2*@@menu.height/3 : nil
        @@menu.move(menu_left, menu_top)
        @@menu.clear do
            background back1, curve: 15
            background back2, curve: 15, width: @@menu.width-4, height: @@menu.height - 4, left: 2, top: 2
			flow margin_left: offset, width: wide, height: high do
                @box = para text, size: size, stroke: stroke, font: font, align: "center", justify: true
            end
		   	
        end

        timer(0) do
			w = @box.width + 20
			h = 30
			debug("w is #{w}, h is #{h}")
			@@menu.style width: w, height: h
			@@menu.show 
		end 
    end

    def hide
        @@menu.hide
    end
end 


Shoes.app(title: "Open Skillwheel v:0.70, database: HoMM 5.5 RC8b", width: 1000, height: 730, resizable: false ) do

        @tooltip = tooltip()

        def sign (slot=nil, text=nil, width=nil, height=nil, border=nil, background=nil, font=nil, size=nil, stroke=nil )
            slot.hover { @tooltip.show text: text, width: width, height: height, border: border, background: background , font: font , size: size, stroke: stroke }
            slot.leave { @tooltip.hide }
        end
        sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 100, top: 100 ), "All settings", 200, 200, rgb(0,20,5,0.5), rgb(0,244,99,0.5), "Vivaldi", 20, brown
        sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 320, top: 100 ), "Mandatory settings only", 200, 200
        sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 620, top: 100 ), "just text. Error message should appear when hovered"
end
```

**Comment by BackOrder** [comment] 2016-12-02 22:09
You are referring to this [message](https://github.com/Shoes3/shoes3/issues/219#issuecomment-256840989).

The reason is related to the order of execution in Shoes prevent to have some information during creation of Shoes objects and is available until much later at runtime. The classic workaround is to use a dummy `timer(0) { }` which ensure whatever is enclosed will be ran only at runtime, after all Shoes objects are effectively created and readily available.

**Comment by dredknight** [comment] 2016-12-03 09:34
You confuse me... isnt this what is done in the code above? @Box element is created and then its length is evaluated in the timer() block? Doh...

**Comment by dredknight** [comment] 2016-12-07 19:36
Alright some good and some bad news. Good news is that progress is undergoing very good! Bad news is I found an unexplainable glitch.

For the purpose of example I use @BackOrder code with stripped top, left and width.
This one is his code just stripped the flows and stacks out of geometry definitions. 
It works as expected.
```Ruby
Shoes.app(width: 250, height: 250) do
    @menu = stack do end
    @menu.clear do
        @b = background blue, curve: 15
        @b2 = background yellow, curve: 15, left: 2, top: 2, height: @menu.height - 4
        flow  do
            @p = para "Say hello!"
        end
        timer(0) { 
            debug("height is #{@p.height} width is #{@p.width}")
            @b.width = @p.width + 20
            @b2.width = @b.width - 4
        }
    end
end
```

Now Try this code. Which is the same as the one above. The only difference is in the  "hello world" string which is translated on 2 rows instead of one.  Check the difference in the debug between the 2 codes.
Why when adding a new line symbol the WIDTH suddenly goes of the charts ? It always becomes the size of the app.width no matter what is the length of the string.

```Ruby
Shoes.app(width: 250, height: 250) do
    @menu = stack do end
    @menu.clear do
        @b = background blue, curve: 15
        @b2 = background yellow, curve: 15, left: 2, top: 2, height: @menu.height - 4
        flow  do
            @p = para "Say\nhello!"
        end
        timer(0) { 
            debug("height is #{@p.height} width is #{@p.width}")
            @b.width = @p.width + 20
            @b2.width = @b.width - 4
        }
    end
end
```

**Comment by BackOrder** [comment] 2016-12-07 19:53
`@p.width` has a value of 250 even on a single `\n` character. Maybe @ccoupe or @passenger94 has an idea here.

It may be preferable to use multiple para, one per line, and take the largest size para to resize the box.

**Comment by dredknight** [comment] 2016-12-07 20:03
@BackOrder that will do.
 I worry about the case where you want to put text from files in the popup. If the text in the file is not a single line it is presented as a string with \n and the result is the same.

**Comment by BackOrder** [comment] 2016-12-07 20:28
![image](https://cloud.githubusercontent.com/assets/8844578/20985211/81b799f6-bc91-11e6-99f7-967931056b53.png)

```ruby
@@textfile = <<-END
   This is a popup tooltip
   It has been defined in a multiline file
   Thank you for your cooperation.
END


Shoes.app(width: 250, height: 250) do
    @menu = stack do end
    @menu.clear do
        @b = background blue, curve: 15
        @b2 = background yellow, curve: 15, left: 2, top: 2, height: @menu.height - 4
        flow  do
          @p = []
          @@textfile.each_line { |n|
            @p << para(n)
          }
        end
        timer(0) {
            @width = 0
            @height = 0
            @p.each { |n|
               @height += n.height
               @width = n.width > @width ? n.width : @width
            }
			
            info("height is #{@height} width is #{@width}")
            @b.width = @width + 20
            @b2.width = @b.width - 4
        }
    end
end
```

**Comment by passenger94** [comment] 2016-12-07 21:31
Please guys, get rid of that awful time(o) hack, start method exist for just that !!!  There is absolutely no guaranties it will work, it just happen to work in simple cases .... you could easily ending adding blindingly time units until you find by chance the right one, not exactly orthodox Feng Shui !

As for the line, i guess Shoes is expecting a line to fill the available space, it's a line, after all !

For this to work smoothly one must expose the C pango machinery (or equivalent) at the Shoes level, until then it's a hunt for clever workarounds, which is fine and totally in the Shoes spirit, i think. :-)

**Comment by dredknight** [comment] 2016-12-08 15:04
@BackOrder the example you give does not work. I assume the narrow size of the app.width may have misguided you. Here is the same code with higher app width.

```Ruby
@@textfile = <<-END
   This is a popup tooltip
   It has been defined in a multiline file
   Thank you for your cooperation.
END


Shoes.app(width: 1000, height: 250) do
    @menu = stack do end
    @menu.clear do
        @b = background blue, curve: 15
        @b2 = background yellow, curve: 15, left: 2, top: 2, height: @menu.height - 4
        flow  do
          @p = []
          @@textfile.each_line { |n|
            @p << para(n)
          }
        end
        timer(0) {
            @width = 0
            @height = 0
            @p.each { |n|
               @height += n.height
               @width = n.width > @width ? n.width : @width
            }
			
            info("height is #{@height} width is #{@width}")
            @b.width = @width + 20
            @b2.width = @b.width - 4
        }
    end
end
```

@passenger94, ah... this is bad. We are so close and suddenly some C code show stopper shinanigans completely ravage it.

**Comment by BackOrder** [comment] 2016-12-08 15:26
> @BackOrder the example you give does not work. I assume the narrow size of the app.width may have misguided you. Here is the same code with higher app width.

Looking at the info clearly shows that the para's width is taken directly from app.width. We have very little runtime information on fonts, this is always been a problem. You may give a try to the flow's width...

**Comment by dredknight** [comment] 2016-12-20 21:07
Alright here is what I am up to.
Just experiment with @@textfiles variables.

Now I need to work on styling and also I got some vague idea how I can actually add the \n sign but first I need some rest ;).

```Ruby
class Tooltip < Shoes::Widget

    def initialize ()
        motion { |x, y| @move_left = x; @move_top = y }
        @menu1 = stack;
    end

    def show( options={} )
        offset, text, stroke, size, font, back1, back2 = 10, options[:text], options[:stroke], options[:size], options[:font],  options[:border] || rgb(120,42,5,0.5), options[:background] || rgb(180,150,110,0.7)
		menu_left, menu_top = @move_left, @move_top;
		@menu1.clear { @@menu = stack height: 0 do end.hide }
        @@menu.clear do
			@p = para "#{text.gsub(/\n/, " ")}", align: "center"
			start do
				@w, @h, @threshold_w, @threshold_h = @p.width, @p.height, 0.5, 0.8
				while @w.to_f/app.width > @threshold_w
					@w=(@w*0.91).to_i; @h=(@h*1.1).to_i
					@h.to_f/app.height > @threshold_h ? ( @w=(@w*1.1).to_i; @h=(@h*0.91).to_i; @threshold_w==1.0 ? break : @threshold_w+=0.1 ) : nil
				end
				@@menu.style width: @w, height: @h
				@@menu.prepend do
					background back1, curve: 15
					background back2, curve: 15, width: @@menu.width - 4, height: @@menu.height - 4, left: 2, top: 2
				end
				@move_left + @@menu.width >= app.width + offset ? menu_left =  app.width - @@menu.width  : nil
				@move_top + @@menu.height >= app.height + offset ? menu_top = app.height - @@menu.height : nil
				@@menu.move(menu_left, menu_top)
			end 
        end
		@@menu.show 
    end

    def hide
        @@menu.hide
    end
end 

@@textfile = <<-END
This is a popup tooltip
This is a popup tooltip
This is a popup tooltip
This is a popup tooltip
This is a popup tooltip
This is a popup tooltip
This is a popup tooltip
This is a popup tooltip asad as a as 
END

@@textfile2 = "qwewqewqe qwewqe qe qw qwe qw wT"
Shoes.app(title: "Open Skillwheel v:0.70, database: HoMM 5.5 RC8b", width: 700, height: 700, resizable: false ) do

    @tooltip = tooltip()

    def sign (slot=nil, options={} )
        slot.hover { @tooltip.show text: options[:text], styling: options[:styling] }
        slot.leave { @tooltip.hide }
    end	
    sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 50, top: 50 ), text: @@textfile
    sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 300, top: 400 ), text: @@textfile
    sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 500, top: 400 ), text: @@textfile2
end
```

**Comment by BackOrder** [comment] 2016-12-20 23:40
@dredknight you did a fantastic job! It looks good, it works well.

For others, take a look at the screenshot:
![image](https://cloud.githubusercontent.com/assets/8844578/21372182/b397c912-c6e3-11e6-9610-87c15d5c8b27.png)

**Comment by dredknight** [comment] 2016-12-22 12:36
Thank you @BackOrder,

Here is another iteration of the code. All style options are now added. you can set font, size, colour of the border and the background. All stuff said for the old code are now valid for this one (https://github.com/Shoes3/shoes3/wiki/Tooltips-Fun) with the following exception.

DECISION MAKING: If you dont add add height and width (or just one of them is defined) the popup will be automatically resize the text box. If no text is defined the tooltip will say "Oh my! No text defined!".

BUGS: It may be possible for very few fonts not to be resized correctly due to their extreme weirdness ( Vivaldi has small issue with height but I managed to work it around).  I expect 95% of the fonts to be ok.

STABILITY: As far as how the code manages in complex environment I use the same technique from the old tooltip which is tested in a constantly changing environment ( total rewrites of the canvas and a couple of layers). Currently the old code is been downloaded ~500 times and no issues are reported.

```Ruby
class Tooltip < Shoes::Widget

    def initialize ()
        motion { |x, y| @move_left = x; @move_top = y }
        @menu1 = stack;
    end

    def show( options={} )
        offset, text, stroke, size, font, back1, back2, @w, @h = 5, options[:text] || "Oh my! no text defined!", options[:stroke], options[:size], options[:font],  options[:border] || rgb(120,42,5,0.5), options[:background] || rgb(180,150,110,0.7), options[:width] || nil, options[:height] || nil
		menu_left, menu_top = @move_left, @move_top;
		@menu1.clear { @@menu = stack height: 0 do end.hide }
        @@menu.clear do
			text_box = stack(displace_left: offset, displace_top: offset) { @p = para "#{text.gsub(/\n/, " ")}", align: "center", font: font, size: size, stroke: stroke }
			start do
				if @w == nil || @h == nil then
					@w, @h, @threshold_w, @threshold_h = @p.width, @p.height, 0.5, 0.8
					while @w.to_f/app.width > @threshold_w
						@w=(@w*0.95).to_i; @h=(@h*1.057).to_i
						@h.to_f/app.height > @threshold_h ? ( @w=(@w*1.057).to_i; @h=(@h*0.95).to_i; @threshold_w==1.0 ? break : @threshold_w+=0.1 ) : nil
					end
					@p.height + 10 > @h ? @h = @p.height + 10 : nil
				end
				text_box.style width: @w, height: @h
				@@menu.style width: @w+2*offset, height: @h + 2*offset				
				@@menu.prepend do
					background back1, curve: 15
					background back2, curve: 15, width: @@menu.width - 4, height: @@menu.height - 4, left: 2, top: 2
				end
				@move_left + @@menu.width >= app.width + offset ? menu_left =  app.width - @@menu.width  : nil
				@move_top + @@menu.height >= app.height + offset ? menu_top = app.height - @@menu.height : nil
				@@menu.move(menu_left, menu_top)
			end 
        end
		@@menu.show 
    end

    def hide
        @@menu.hide
    end
end 

  TIPS = [
        "People who think they know everything are a great annoyance to those of us who do.",
        "Stop thinking, and end your problems.",
        "I was never one to patiently pick up broken fragments and glue them together again and tell myself that the mending whole was good as new. What is broken is broken – and I’d rather remember it as it was at its best than mend it and see the broken places as long as I lived.",
        "One can laugh about anything but not with everybody.",
        "Step in someone's Shoes, a thousand miles before judging him.'",
		"Maybe our old wounds teach us something. They remind us where we’ve been and what we’ve overcome. They teach us lessons about what to avoid in the future. That’s what we like to think. But that’s not always the way it is. Sometimes there are things we just have to learn over again."
    ]

Shoes.app(title: "Tooltip test", width: 700, height: 700, resizable: false ) do

    @tooltip = tooltip()

    def sign (slot=nil, options={} )
        slot.hover { @tooltip.show text: options[:text], header: options[:header] , text2: options[:text2], font: options[:font], size: options[:size], width: options[:width], height: options[:height], border: options[:border], background: options[:background], stroke: options[:stroke] }
        slot.leave { @tooltip.hide }
    end	
    sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 50, top: 50 ), text: TIPS[rand(TIPS.size)], font: "Vivaldi", size: 15
    sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 300, top: 400 ), text: TIPS[rand(TIPS.size)], width: 30, height: 200, border: green, background: yellow
    sign ( image "#{DIR}/static/app-icon.png", width: 200, height: 200, left: 500, top: 400 ), text: TIPS[rand(TIPS.size)], stroke: red
end
```
![image](https://cloud.githubusercontent.com/assets/12410314/21425649/290aa05a-c853-11e6-9cbb-fe4ae8eb5045.png)

**Comment by dredknight** [comment] 2016-12-22 12:39
I have one question though. is there a way to summarize this code

```Ruby
def sign (slot=nil, options={} )
        slot.hover { @tooltip.show text: options[:text], header: options[:header] , text2: options[:text2], font: options[:font], size: options[:size], width: options[:width], height: options[:height], border: options[:border], background: options[:background], stroke: options[:stroke] }
        slot.leave { @tooltip.hide }
    end
```
Into that code

```Ruby
def sign (slot=nil, options={} )
        slot.hover { @tooltip.show options={} }
        slot.leave { @tooltip.hide }
    end	
```

**Comment by dredknight** [comment] 2016-12-26 11:10
Alright some food for thought. Please compare the debug output of both codes below.
```Ruby
Shoes.app do 
	@p = para "Lets do it"
	info ("para width is #{@p.width}")
end
```
Width is 0

```Ruby
Shoes.app do 
	@p = para "Lets do it"
	start do
		info ("para width is #{@p.width}")
	end
end
```
Width is 72

I get it that when the evaluation is executed with start the paragraph is already drawn so it can take the width. But why is the drawing required to evaluate the width at first place? cant it be done while not drawn?

Regarding the resizing code above it there is small drawback. Due to the dynamic resizing it works slower so if you put a number of elements close to each other and each of them has popup and you go from one to another of them with the mouse fast  The new one wont trigger. 

For example this is not very good for my app because it has about 130 popup elements distributed closely to each other. There should be a way to speed up the resizing.

**Comment by passenger94** [comment] 2016-12-26 12:59
Under the hood in C code there is a Pango library which deals with everything font and text related, that library have the tooling necessary to convert an abstract text into some concrete pixels, given font size etc..., so until drawing (in Shoes gui) is not finished Shoes has no way to know precisely how much space that text is going to take.

For the slow down you experienced, it's a known limitation, the more text you have the more strain you put on Shoes drawings (for example, try to render a very long para and see how scrolling becomes slow ...). Here not only there is a bunch of different texts widget but also lots of popups, with their own calculations requirement and every time you trigger a pop up Shoes have to re-draw entirely the gui, you have a lot of images also, if i remember correctly, (same when you trigger the leave event) and remember drawing are asynchronous, they happen when Shoes is idle, so if you trigger quickly enough lots of drawing events( hover, leave, ..) shoes might be busy enough to "skip" some of them ...

I would suggest to have only one popup for your entire application and dynamically refresh it, if at all possible of course (only one at a time should be necessary ?)

Happy Shoes year !

**Comment by dredknight** [comment] 2016-12-27 14:59
Thanks for the revelations @passenger94. Actually this is how it works - one popup that is cleaned and refreshed with new stuff every time it is required. You are right about the rendering, I did compare 2 resizing methods - the one is the one you see above where I take the width from the para, the second one disregards the text and recalculates the box depending on the number of chars multiplied by height and size numbers set for the the current size and font. That second method is what I use for the big app because it works without delay. It also has 3 paras inside the tooltip (Header, text1 and text2) and it is still faster.

**Comment by BackOrder** [comment] 2016-12-27 15:26
The advice from @passenger94 is very good. Numinoes is extensively recycling Shoes elements to circumvent such problems aforementioned. Shoes becomes easily overwhelmed when its number of elements raise. Numinoes has roughly 70ish elements at any given time, 64 of which are used for the game board. The elements are kept in an array to be able to update them rather than create new elements and draw over.

You should also consider thinking in Shoes UI way. Shoes is not meant to reproduce common UI. So, if a popup text would be too long, how about shorten it and add **back** and **forth** buttons at the bottom right corner?

**Comment by dredknight** [comment] 2017-01-17 21:16
Thank you for all the advice!
I got back on the issue and possibly I may go around this issue by another approach.

However I wonder if there is a way to deduce the width and height of a char based on the string size. 
For example:
```Ruby
text = "whats up dog?"
debug("size is #{text.size})
-> size is 9
```

if it is possible to deduce the average width and height depending on the size I can use the char count to evaluate the size requirements for the text on the go. And it will happen much much faster than the current method.

**Comment by BackOrder** [comment] 2017-01-17 22:25
The size method only returns the number of characters. The problem will arise when you are using non-monospaced, that is, without a fixed width. In a monospaced font, you could say `(char width) * text.size` but the same calculation won't work on a non-monospaced font because some letters might have a bigger or smaller size than others.

**Comment by ccoupe** [comment] 2017-01-18 00:17
Height is even more confusing to guess for some fonts. This was identified as something useful in #266  It would be nice to provide this info but we need a new class and font isn't it.  Ruby's string is not a good place to install Shoes methods. Every name I've dreamed up feels wrong.

**Comment by BackOrder** [comment] 2017-01-18 00:26
> Every name I've dreamed up feels wrong.

Do you mean instead of **text_shape**? [Type](https://en.wikipedia.org/wiki/Sort_(typesetting)) or [Glyph](https://en.wikipedia.org/wiki/Glyph) would be descriptive.

**Comment by ccoupe** [comment] 2017-01-18 01:25
isn't Type in use or misleading if not? We don't directly call textblock but it's in the manual. perhaps `textmeasure, string, {sytles}` and it returns turns [w,h] - we want to measure a string with all its pangocairo attributes. Still, textmeasure doesn't feel that good.  I believe the pangocairo calls are part of the charting widget so it just a matter of picking a name and wiring it into ruby.c and someplaces like canvas.h,

**Comment by BackOrder** [comment] 2017-01-18 02:35
**Type** is representative when it comes to printing, it is not a reserved keyword in Ruby but it could indeed be misleading for a programmer. We could use alternatively **typesetting**: [Typesetting is the composition of text by means of arranging physical types or the digital equivalents.](https://en.wikipedia.org/wiki/Typesetting)

The whole process sounds like [font rasterization](https://en.wikipedia.org/wiki/Font_rasterization). Does text_shape support anti-aliasing? (Maybe we should move this conversation to #266)

I like **glyph** but the meaning is not as strong as those above.

Are we both talking about text_shape? You mention in #266 that text_shape returns a box with rendered text rather than [w, h].

**Comment by ccoupe** [comment] 2017-01-18 03:05
It's not really the same as #266 text_shape although #266 would use similar C code. This issue, #294 is not the first time this capability was asked for. In this proposal we are not drawing anything on screen or saving something (like a shape) for later display. I'll add a comment to #266 to address your questions about it.

**Comment by BackOrder** [comment] 2017-01-18 03:21
Got it now. Could we just extend **TextBlock** with measurement methods (width, height) and rendering (text_shape)? For example, Slot does have width and height methods. It would make much more sense to extend TextBlock than adding to the dsl.

**Comment by ccoupe** [comment] 2017-01-18 03:44
adding a 'measure` method to TextBlock is appealing. So
```ruby
 @p =  para "here's my string", font: "Arial-18-Italic"
w, h = @p.measure
```
Sadly that puts the para in the slot (configures the slot)  before we measure it and I think @dredknight wants to know the size so he can set the slot size before.

**Comment by BackOrder** [comment] 2017-01-18 03:49
This should work. He already resizes the slot in the `start` block, which means he should be able to get runtime information such as TextBlock#measure would provide.

**Comment by ccoupe** [comment] 2017-01-18 06:03
You can can get width and height from a textblock already.  No need for a new feature like #298. Getting confused.

**Comment by BackOrder** [comment] 2017-01-18 07:18
A simple test should determine whether the feature is necessary or not. Does the values from TextBlock are the same from the text actual measures?

**Comment by ccoupe** [comment] 2017-01-18 07:23
I await the test results. Got enough on my plate.

**Comment by BackOrder** [comment] 2017-01-30 18:24
@dredknight if you are willing to share, I'd like to suggest again to include this into samples as **expert-widget-tooltip.rb**. We could tag it for 3.3.3 or something. You came up with something Shoes users will certainly enjoy.

**Comment by BackOrder** [comment] 2017-01-30 18:26
Shall we close this issue? The tooltip itself is working. Text measurement is an entirely different issue.

**Comment by dredknight** [comment] 2017-01-30 18:48
We pushed Shoes as far as possible so I believe it is over.

**Comment by BackOrder** [comment] 2017-01-30 18:51
Thanks @dredknight

**Closed by BackOrder** 2017-01-30 18:51 UTC
