### ISSUE TITLE
Sticky header

### ISSUE THREAD

**Issue by Dassadar** [Shoes3/shoes3#112] opened 2015-04-12 07:09 UTC
Hello,

Is there an easy way to do a sticky header in shoes please?
I want to have a sticky menu on top of the app, but cannot figure out which stack/flow property to use...

Regards,
Dassadar

**Comment by passenger94** [comment] 2015-04-12 07:38
Hi 
you can do this
```ruby
Shoes.app do
   stack margin_top: 60 do   # leaving room for the header
       (0..50).map {|n| para "\t#{n}"}
   end
   
   flow left: 0, top: 0, height: 60, attach: Shoes::Window do    # stick the slot to the app
       background red
       title "Header"
   end
end
```
Manual is wrong with the attach style, it's `attach => Shoes::Window` not `attach => Window`
thanks for pointing this

**Comment by Dassadar** [comment] 2015-04-12 16:51
Hello,

Thank you.
This works nice, except one thing.
When you scroll down, then the prereserved space on top disappears (your
first stack), and therefore the header is overlapping some other elements.
Is there a way to avoid this?

Regards,
Dassadar

2015-04-12 9:38 GMT+02:00 passenger94 <notifications@github.com>:

**Comment by passenger94** [comment] 2015-04-12 18:20
i don't get it then, because that's what i was expecting for a sticky header !
have you an example showing your expected behavior ?

do you want some other elements to be also sticky ?

**Comment by Dassadar** [comment] 2015-04-12 19:08
just replace "para" by "button" in your upper example, and you will get my
issue...

2015-04-12 20:20 GMT+02:00 passenger94 <notifications@github.com>:

**Comment by passenger94** [comment] 2015-04-12 20:58
Haha ! Elements are overlapping header !! ;-D

ok here comes our old friend : timer(0){}
basically the first slot is not totally "finished" when creating the second slot, definitively a bug
the workaround is to use either a timer block or a start block llike so :
```ruby
Shoes.app do
   stack margin_top: 60 do
       (0..50).map {|n| button "\t#{n}"}
   end.start {
     flow height: 60, attach: Shoes::Window do
         background red
         title "Header"
     end }
end
```
or
```ruby
Shoes.app do
   stack margin_top: 60 do
       (0..50).map {|n| button "\t#{n}"}
   end
 timer(0) {
   flow height: 60, attach: Shoes::Window do
       background red
       title "Header"
   end }
end
```

**Comment by Dassadar** [comment] 2015-04-23 11:47
Still not working in my case which is difficult... The easiest would really be a fix :-/

**Comment by ccoupe** [comment] 2015-04-24 01:23
A fix would be a menu system and that's a big effort and not very shoes like. Try looking at how lib/cobbler.rb manages it its 'panels' underneath a row of buttons. Also, dig around to find a description of how the url/visit scheme works on Shoes. (hackeyhack perhaps).

**Comment by passenger94** [comment] 2015-04-24 13:48
@Dassadar  there's something else you can try, but i'm afraid it's only a variation of the preceding, there's a start style for every slot so :
```ruby
Shoes.app do
  build_sticky = Proc.new {
   flow height: 60, attach: Shoes::Window do
       background red
       title "Header"
   end }
 
   stack margin_top: 60, start: build_sticky do
       (0..50).map {|n| button "\t#{n}"}
   end
end
```

**Comment by ccoupe** [comment] 2015-07-30 03:18
Closing?

**Closed by ccoupe** 2015-07-30 03:18 UTC

**Comment by Dassadar** [comment] 2015-07-30 04:58
Not really, still doesn't work for me.
Is there any development planned to fix maybe?

2015-07-30 5:18 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by Dassadar** [comment] 2016-03-30 18:40
Hello,
Reopening this issue as it is still there.
I managed to reproduce on a small program:

```
Shoes.app do
	flow attach: Shoes::Window do
		background black
		para "test"
	end
	stack do
	       (0..50).map {|n| app.para "\t#{n}"}
	end
end
```

Problem is that scrolling down no longer works.

Can you please help?

Regards,
David

**Comment by passenger94** [comment] 2016-03-30 19:32
Hello,
This has been hopefully fixed 
2 things in your code :
You must provide a height for the attached (stiky slot) and you must write it after the main slot
then if you want to make sure it is drawn above all elements (even natives like edit_lines) you must write it inside a start block which is called once the main slot is drawn
for example :

```ruby
Shoes.app do
    @st = stack margin_top: 50 do
        (0..50).map {|n| edit_line "\t#{n}"}
    end
    
    @st.start {
        flow attach: Shoes::Window, height: 50 do
            background black
            para "test", stroke: white
        end
    }
end
```
you can also put the start block inside the main, like so
```ruby
Shoes.app do
    stack margin_top: 50 do
        (0..50).map {|n| edit_line "\t#{n}"}
        
        start {
            flow attach: Shoes::Window, height: 50 do
                background black
                para "test", stroke: white
            end
        }
    end
end
```

**Comment by ccoupe** [comment] 2016-03-30 21:39
@passenger94 is clever! I was going to say it's working as intended since the purpose of the attach is to stop scrolling and the scroll bar is for the whole window.

**Comment by Dassadar** [comment] 2016-03-30 21:50
Thank you for your help, it now works! :-) (no need of the start)
